version: '3.8'

services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: nginx.prod.dockerfile
    ports:
      - 80:80
      - 443:443

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.prod.dockerfile
